### ISSUE TITLE
Create a separate function for random date

### ISSUE THREAD

**Issue by admwln** [admwln/circle-of-friends#2]
A function which returns a random date and and time in the near future should be separated from the DisplayFriendCircle component, and put in its own file as a helper function.

The logic by which this date and time is calculated is not very important, as long as the resulting year is within reason, and that it can be used by the component DisplayFriendCircle with results comparable to the current version.

**Comment by A-4-Atom** [comment]
@admwln Hi, I'd like to make the necessary changes. Can you assign this issue to me please?

**Comment by admwln** [comment]
@A-4-Atom Thanks for showing interest in this project! I have assigned the issue to you.

**Comment by admwln** [comment]
@A-4-Atom Thank your for your contribution, it works just as I had envisioned it. I will now close this issue.
